latex3/unicode-math

- unicode-math.dtx
Since v2.4, the preferred `fontspec` syntax for `\setmainfont` has the optional font features argument following the mandatory font name argument. Here, `\setmathfont` is changed to follow the same syntax, and the documentation is updated accordingly.
> Change \setmathfont syntax to match fontspec v2.4

- unicode-math-table.tex
It should be ‘U+0332 COMBINING LOW LINE’, which seems to be the below
equivalent of ‘U+0305 COMBINING OVERLINE’ that we use for `\overbar`. This
is also the character Cambria and XITS make extensible.
> Fix \underbar code point

- unicode-math.dtx
Fixes #306.
The problem is that `\mathfence` is eliminated too soon, before `\@@_set_math_fence:nnnn` is run.
I can't think of a correct place to change `\mathfence` to `\mathord`, since loading a new font and having to rerun the setup code could happen at any time.
Leaving `\mathfence` doesn't seem to have any negative consequences.
Test case:
\documentclass{article}
\pagestyle{empty}
\usepackage{IEEEtrantools}
\usepackage{unicode-math}
\setmathfont{XITS Math}
\begin{document}
\begin{IEEEeqnarray*}{c}
|       \quad \left|        \frac12 \right|       \\
\vert   \quad \left\vert    \frac12 \right\vert   \\
\lvert  \quad \left\lvert   \frac12 \right\lvert  \\
\rvert  \quad \left\rvert   \frac12 \right\rvert  \\
\|      \quad \left\|       \frac12 \right\|      \\
\Vert   \quad \left\Vert …
> fix \{,l,r}{v,V,Vv}ert commands

- unicode-math.dtx
This allows for a prospective format update in which the names will be made available without the
\luatex... prefix.
> Allow for 'bare' \cramped... names in LuaTeX

- unicode-math-compat.dtx
- unicode-math.dtx
Based on upcoming kernel changes, this is the best long-term plan. This is the only other case in unicode-math that needs adjustment (after the merge of the \cramped... change).
> Use \Uroot not \luatexUroot

- unicode-math.dtx
This is hard to spot as it's a csname!
This is the last change we need (I think) for the planned kernel update.
> One stray \luatexUmath... removed

- unicode-math-table.tex
They are Arabic math operators with no previous support in TeX (or AMS
table), so I just invented symbol names for them and tried to make them
long to avoid possible clashes.
> Add U+1EEF0 and U+1EEF1 math operator

- unicode-math.dtx
Adds missing subscripts. (I don't know how to test this, so this is completely untested!)
Example tex file:
<pre>
\documentclass{article}
\usepackage{fontspec}
\usepackage{unicode-math}
\setmathfont{xits-math.otf}
\begin{document}
a $xₐ$\\
e $xₑ$\\
h $xₕ$\\
i $xᵢ$\\
j $xⱼ$\\
k $xₖ$\\
l $xₗ$\\
m $xₘ$\\
n $xₙ$\\
o $xₒ$\\
p $xₚ$\\
r $xᵣ$\\
s $xₛ$\\
t $xₜ$\\
u $xᵤ$\\
x $xₓ$\\
\end{document}
</pre>
See also:
https://github.com/khaledhosny/xits-math/issues/42
http://www.unicode.org/charts/PDF/U2070.pdf
> Add missing subscripts (U+2096 - U+209C)

- unicode-math-compat.dtx
Also, streamlines nested `AtEndOfPackageFile` (issue #367).
```
modified:   unicode-math-compat.dtx
```
> Fix #345: `\newfam` disturbs math alphabets

- unimath-symbols.ltx
Since [DejaVu has a dedicated math font now](https://github.com/dejavu-fonts/dejavu-fonts/releases/tag/version_2_36), I thought it should be included among the example fonts.
> Include DejaVu Math TeX Gyre in the table(s) of symbols.

- unimath-symbols.ltx
The name "DejaVu Math TeX Gyre" was not rendered correctly (it had no spaces).
> Fix source order and formatting in symbol list.

- unimath-symbols.ltx
This is a somewhat more invasive change, since it involves adding three package dependencies to the symbols list source.
> Fix overfull hboxes once and for all.

- unicode-math.dtx
So far only in XeTeX the otf-file parameters `ScriptPercentScaleDown` and `ScriptScriptPercentScaleDown` were honored by the loading routines. This commit patches `\@@_declare_math_sizes` in order to get the same behavior for luatex.
> Luatex: use scriptstyle sizes from the otf file if available

- unicode-math-doc.tex
> fix typo in doc

- um-code-amsmath.dtx
- um-code-compat.dtx
- um-code-epilogue.dtx
READY
Avoid deprecation warnings.
The following now works.
```
\documentclass{article}
\usepackage[enable-debug]{expl3}
\ExplSyntaxOn \debug_on:n { deprecation } \ExplSyntaxOff
\usepackage{unicode-math}
\begin{document}
\[
a = b
\]
\end{document}
```
> Rename deprecated expl3 command

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
**READY/UNDER DEVELOPMENT/FOR DISCUSSION**
https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting
> enable syntax highlighting on GitHub [ci skip]

- um-doc-style.tex
- unimath-symbols.ltx
**READY/UNDER DEVELOPMENT/FOR DISCUSSION**
`\GetFileInfo` does not work, so `\umfiledate` and `\umfileversion` are not resolved (`? ?`) in unimath-symbols.pdf ([CTAN link](http://mirrors.ctan.org/macros/latex/contrib/unicode-math/unimath-symbols.pdf)).
In this PR I remove `\GetFileInfo` and use date as defined in https://github.com/wspr/unicode-math/blob/1dae0d160438ec7d3cd5487af341348e8ff42bac/unicode-math.dtx#L69-L73
> Fix date in unimath-symbols.pdf

- um-code-sscript.dtx
Extremely minor.
Just added a few superscripts for greek letters.
```tex
\documentclass{article}
\usepackage{unicode-math}
\begin{document}
\[
aᵝ,aᵞ,aᵟ,aᵠ, bᵡ
\]
\end{document}
```
> a few additional subscripts, greek letters

- unicode-math-table.tex
**READY/UNDER DEVELOPMENT/FOR DISCUSSION**
Simply remove some spaces in `unicode-math-table.tex`.
Some questions:
- Why there are something like `b:`, `p:`, `/neg /lnot`? It seems unnecessary and confusing.
- In Unicode 11.0, some math related symbols have been added into the [Miscellaneous Symbols and Arrows](https://www.unicode.org/charts/PDF/Unicode-11.0/U110-2B00.pdf) block. Do you have plan to add them into `unicode-math-table.`?
> remove spaces in unicode-math-table.tex

- um-doc-main.tex
**READY**
§5.1 misses `math-style=literal`.
> [doc] add missing `literal` candidate for `math-style`

- unicode-math.dtx
**READY/UNDER DEVELOPMENT/FOR DISCUSSION**
There are several other engines (e.g. upTeX) in the standard TeX distribution, but `unicode-math` does not support them. I simply give an error message here, followed by `\endinput`.
> Error message for other engines

- um-code-main.dtx
- um-code-opening.dtx
**READY**
`unicode-math` sets `\fontdimen`s to emulate either traditional TeX or XeTeX fonts. Since this functionality is  usefful n a more general context than just with `unicode-math`, it has been added to `luaotfload` directly. This changes `unicode-math` to make use of this new `luaotfload` functionality and therefore makes font loading faster, avoids caching issues, does not require to load fonts with weird scaling factors and simplifies the code.
The current code still loads the family 2/3 funts scaled by 0.9999/1.001 to avoid small changes to existing documents and keep compatibility with XeTeX.
n/a (Only refactors existing functionality)
> Use mathfontdimen font feature in LuaTeX

- unimath-symbols.ltx
**READY**
adds 
```
\defmathfont{ncm}{NewCMMath-Regular.otf}{AA66AA}{N}
\defmathfont{gnh}{GFSNeohellenicMath.otf}{AAAA66}{H}
\defmathfont{erm}{Erewhon-Math.otf}{66AA66}{E}
```
Could add more but perhaps a complete redesign would be needed in that case, the table is getting a bit wide
also switches out tabu package
doc change only
> additional fonts for #596

- um-doc-main.tex
A dash was missing between 𝔸 and ℤ in the description of the range of the double-struck style: it was {𝕒–𝕫,𝔸ℤ}
> Really minor typo in the doc

- unimath-symbols.ltx
**FOR DISCUSSION**
Only one file is changed in this commitment, that is, `unimath-symbols.ltx`. No functional change is appended to this repository; only a documentation (`texdoc unimath-symbols`) is influenced.
To maintain consistency with other subsubsections, commas are added before the word “Greek” in section titles containing the keyword “Greek”. It will be easier for a user to find information in section 13 (\mathalpha) after this commitment.
No new or fixed functionality. `unimath-symbols.ltx` and source files of symbol documentations for other fonts require to be recompiled to generate updated documentations.
> Add commas to subsubsection titles with “Greek” in unimath-symbols.ltx
